homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Appliances

http:

frontend:

view_event:

sleepiq: !include sleepiq.yaml
neato: !include neato.yaml
litter_robot: !include litter_robot.yaml
