homeassistant:
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Appliances

http:
  server_port: !secret appliance_server_port

frontend:

sleepiq: !include sleepiq.yaml
neato: !include neato.yaml
litter_robot: !include litter_robot.yaml
