homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Appliances
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

# view_event:
#   name: appliacnes
#   components:
#     - camera
#     - neato
#     - sleepiq

http:
#  base_url: https://automation.prettybaked.com
#  server_port: !secret appliances_server_public_port
  
frontend:

config:

sleepiq: !include sleepiq.yaml
neato: !include neato.yaml
litter_robot: !include litter_robot.yaml

mqtt: !include mqtt.yaml
# mqtteventstream: !include eventstream.yaml
mqtt_remoteinstance: !include mqtt_remoteinstance.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.mqtt_remoteinstance: debug
